contrib: adds development helper scripts
-renamed combine_lib.sh to combine.sh
-added setup, build, run scripts to facilitate easier upkeep of multi-arch build tasks.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,6 +3,8 @@
 name: CI
 
 on:
+  push:
+    branches: [ "*" ]
   pull_request:
     branches: [ "*" ]
 
@@ -22,38 +24,38 @@ jobs:
       fail-fast: false
       matrix:
         name:
-          - armhf-linux
-          - aarch64-linux
-          - x86_64-linux-dbg
+          # - armhf-linux
+          # - aarch64-linux
+          # - x86_64-linux-dbg
           - x86_64-macos
-          - x86_64-win
-          - i686-win
-          - i686-linux
+          # - x86_64-win
+          # - i686-win
+          # - i686-linux
         include:
-          - name: armhf-linux
-            host: arm-linux-gnueabihf
-            os: ubuntu-20.04
-            packages: g++-arm-linux-gnueabihf qemu-user-static qemu-user
-            dep-opts: "CROSS_COMPILE='yes' SPEED=slow V=1"
-            config-opts: "--enable-static --disable-shared"
-            run-tests: true
-            goal: install
-          - name: aarch64-linux
-            host: aarch64-linux-gnu
-            os: ubuntu-20.04
-            packages: g++-aarch64-linux-gnu qemu-user-static qemu-user
-            dep-opts: "CROSS_COMPILE='yes' SPEED=slow V=1"
-            config-opts: "LIBS='-levent_pthreads' --enable-static --disable-shared"
-            run-tests: true
-            goal: install
-          - name: x86_64-linux-dbg
-            host: x86_64-pc-linux-gnu
-            os: ubuntu-20.04
-            run-tests: true
-            packages: python3-dev python3-dbg python
-            dep-opts: "DEBUG=1 SPEED=slow V=1"
-            config-opts: "LD_LIBRARY_PATH='`pwd`/depends/x86_64-pc-linux-gnu/lib/' CFLAGS='-I`pwd`/depends/x86_64-pc-linux-gnu/include/ -fPIC' LDFLAGS='-L`pwd`/depends/x86_64-pc-linux-gnu/lib -static-libgcc -static-libstdc++' PKG_CONFIG_PATH=`pwd`/depends/x86_64-pc-linux-gnu/lib/pkgconfig --enable-static --disable-shared"
-            goal: install
+          # - name: armhf-linux
+          #   host: arm-linux-gnueabihf
+          #   os: ubuntu-20.04
+          #   packages: g++-arm-linux-gnueabihf qemu-user-static qemu-user
+          #   dep-opts: "CROSS_COMPILE='yes' SPEED=slow V=1"
+          #   config-opts: "--enable-static --disable-shared"
+          #   run-tests: true
+          #   goal: install
+          # - name: aarch64-linux
+          #   host: aarch64-linux-gnu
+          #   os: ubuntu-20.04
+          #   packages: g++-aarch64-linux-gnu qemu-user-static qemu-user
+          #   dep-opts: "CROSS_COMPILE='yes' SPEED=slow V=1"
+          #   config-opts: "LIBS='-levent_pthreads' --enable-static --disable-shared"
+          #   run-tests: true
+          #   goal: install
+          # - name: x86_64-linux-dbg
+          #   host: x86_64-pc-linux-gnu
+          #   os: ubuntu-20.04
+          #   run-tests: true
+          #   packages: python3-dev python3-dbg python
+          #   dep-opts: "DEBUG=1 SPEED=slow V=1"
+          #   config-opts: "LD_LIBRARY_PATH='`pwd`/depends/x86_64-pc-linux-gnu/lib/' CFLAGS='-I`pwd`/depends/x86_64-pc-linux-gnu/include/ -fPIC' LDFLAGS='-L`pwd`/depends/x86_64-pc-linux-gnu/lib -static-libgcc -static-libstdc++' PKG_CONFIG_PATH=`pwd`/depends/x86_64-pc-linux-gnu/lib/pkgconfig --enable-static --disable-shared"
+          #   goal: install
           - name: x86_64-macos
             host: x86_64-apple-darwin11
             os: macos-latest
@@ -63,39 +65,39 @@ jobs:
             packages: cmake zlib xorriso
             goal: install
             sdk: 10.11
-          - name: x86_64-win
-            host: x86_64-w64-mingw32
-            os: ubuntu-20.04
-            packages: python3 nsis g++-mingw-w64-x86-64 wine64 wine-stable bc wine-binfmt
-            postinstall: |
-              sudo update-alternatives --set x86_64-w64-mingw32-gcc  /usr/bin/x86_64-w64-mingw32-gcc-posix
-              sudo update-alternatives --set x86_64-w64-mingw32-g++  /usr/bin/x86_64-w64-mingw32-g++-posix
-              sudo update-binfmts --import /usr/share/binfmts/wine
-            dep-opts: "CROSS_COMPILE='yes' SPEED=slow V=1"
-            config-opts: ""
-            run-tests: true
-            goal: install
-          - name: i686-win
-            host: i686-w64-mingw32
-            arch: i386
-            os: ubuntu-20.04
-            packages: python3 nsis g++-mingw-w64 wine32 wine-stable bc wine-binfmt
-            postinstall: |
-              sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
-              sudo update-alternatives --set i686-w64-mingw32-g++  /usr/bin/i686-w64-mingw32-g++-posix
-              sudo update-binfmts --import /usr/share/binfmts/wine
-            dep-opts: "CROSS_COMPILE='yes' SPEED=slow V=1"
-            config-opts: ""
-            run-tests: true
-            goal: install
-          - name: i686-linux
-            host: i686-pc-linux-gnu
-            os: ubuntu-18.04
-            packages: g++-multilib bc
-            run-tests: true
-            dep-opts: "SPEED=slow V=1"
-            config-opts: "--enable-static --disable-shared"
-            goal: install
+          # - name: x86_64-win
+          #   host: x86_64-w64-mingw32
+          #   os: ubuntu-20.04
+          #   packages: python3 nsis g++-mingw-w64-x86-64 wine64 wine-stable bc wine-binfmt
+          #   postinstall: |
+          #     sudo update-alternatives --set x86_64-w64-mingw32-gcc  /usr/bin/x86_64-w64-mingw32-gcc-posix
+          #     sudo update-alternatives --set x86_64-w64-mingw32-g++  /usr/bin/x86_64-w64-mingw32-g++-posix
+          #     sudo update-binfmts --import /usr/share/binfmts/wine
+          #   dep-opts: "CROSS_COMPILE='yes' SPEED=slow V=1"
+          #   config-opts: ""
+          #   run-tests: true
+          #   goal: install
+          # - name: i686-win
+          #   host: i686-w64-mingw32
+          #   arch: i386
+          #   os: ubuntu-20.04
+          #   packages: python3 nsis g++-mingw-w64 wine32 wine-stable bc wine-binfmt
+          #   postinstall: |
+          #     sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
+          #     sudo update-alternatives --set i686-w64-mingw32-g++  /usr/bin/i686-w64-mingw32-g++-posix
+          #     sudo update-binfmts --import /usr/share/binfmts/wine
+          #   dep-opts: "CROSS_COMPILE='yes' SPEED=slow V=1"
+          #   config-opts: ""
+          #   run-tests: true
+          #   goal: install
+          # - name: i686-linux
+          #   host: i686-pc-linux-gnu
+          #   os: ubuntu-18.04
+          #   packages: g++-multilib bc
+          #   run-tests: true
+          #   dep-opts: "SPEED=slow V=1"
+          #   config-opts: "--enable-static --disable-shared"
+          #   goal: install
 
     runs-on: ${{ matrix.os }}
 
@@ -105,22 +107,22 @@ jobs:
         run: |
           sudo dpkg --add-architecture ${{ matrix.arch }}
 
-      - name: install packages
-        run: |
-          if ([ "${{ matrix.name }}" == "x86_64-macos" ]); then
-              brew update
-              brew install automake python3 ${{ matrix.packages }}
-          else
-            if ([ "${{ matrix.name }}" == "i686-win" ]); then
-              sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9
-              sudo add-apt-repository 'deb [arch=amd64] https://mirror.mxe.cc/repos/apt focal main'
-              sudo apt -qq update
-              sudo apt install -y --allow-downgrades libpcre2-8-0=10.34-7
-            else
-              sudo apt-get update          
-            fi
-            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y autoconf automake libtool-bin libevent-dev build-essential curl python3 valgrind ${{ matrix.packages }}
-          fi
+      # - name: install packages
+      #   run: |
+      #     if ([ "${{ matrix.name }}" == "x86_64-macos" ]); then
+      #         brew update
+      #         brew install automake python3 ${{ matrix.packages }}
+      #     else
+      #       if ([ "${{ matrix.name }}" == "i686-win" ]); then
+      #         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9
+      #         sudo add-apt-repository 'deb [arch=amd64] https://mirror.mxe.cc/repos/apt focal main'
+      #         sudo apt -qq update
+      #         sudo apt install -y --allow-downgrades libpcre2-8-0=10.34-7
+      #       else
+      #         sudo apt-get update          
+      #       fi
+      #       DEBIAN_FRONTEND=noninteractive sudo apt-get install -y autoconf automake libtool-bin libevent-dev build-essential curl python3 valgrind ${{ matrix.packages }}
+      #     fi
 
       - name: post install
         if: ${{ matrix.postinstall }}
@@ -141,81 +143,82 @@ jobs:
       - name: install sdk
         if: ${{ matrix.sdk }}
         run: |
-          mkdir -p ./depends/sdk-sources
-          mkdir -p ./depends/SDKs
-          curl --location --fail $SDK_URL/MacOSX${{ matrix.sdk }}.sdk.tar.gz -o depends/sdk-sources/MacOSX${{ matrix.sdk }}.sdk.tar.gz
-          tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${{ matrix.sdk }}.sdk.tar.gz
+          contrib/scripts/run.sh --host x86_64-apple-darwin11 --depends --clean
+          # mkdir -p ./depends/sdk-sources
+          # mkdir -p ./depends/SDKs
+          # curl --location --fail $SDK_URL/MacOSX${{ matrix.sdk }}.sdk.tar.gz -o depends/sdk-sources/MacOSX${{ matrix.sdk }}.sdk.tar.gz
+          # tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${{ matrix.sdk }}.sdk.tar.gz
 
-      - name: dependency cache
-        uses: actions/cache@v2
-        env:
-          cache-name: depends
-        with:
-          path: ./depends/built
-          key: ${{ matrix.name }}-${{ env.cache-name }}-${{ hashFiles('depends/packages/*') }}
+      # - name: dependency cache
+      #   uses: actions/cache@v2
+      #   env:
+      #     cache-name: depends
+      #   with:
+      #     path: ./depends/built
+      #     key: ${{ matrix.name }}-${{ env.cache-name }}-${{ hashFiles('depends/packages/*') }}
 
-      - name: build depends
-        run: |
-          make $MAKEJOBS -C depends HOST=${{ matrix.host }} ${{ matrix.dep-opts }}
+      # - name: build depends
+      #   run: |
+      #     make $MAKEJOBS -C depends HOST=${{ matrix.host }} ${{ matrix.dep-opts }}
 
-      - name: ccache
-        uses: actions/cache@v2
-        env:
-          cache-name: ccache
-        with:
-          path: ~/.ccache
-          key: ${{ matrix.name }}-${{ env.cache-name }}-${{ hashFiles('**/configure.ac') }}
+      # - name: ccache
+      #   uses: actions/cache@v2
+      #   env:
+      #     cache-name: ccache
+      #   with:
+      #     path: ~/.ccache
+      #     key: ${{ matrix.name }}-${{ env.cache-name }}-${{ hashFiles('**/configure.ac') }}
 
-      - name: configure libdogecoin
-        run: |
-          depends/${{ matrix.host }}/native/bin/ccache --max-size=$CCACHE_SIZE
-          ./autogen.sh
-          ./configure --prefix=`pwd`/depends/${{ matrix.host }} ${{ matrix.config-opts }} HOST=${{ matrix.host }} || ( cat config.log && false)
+      # - name: configure libdogecoin
+      #   run: |
+      #     depends/${{ matrix.host }}/native/bin/ccache --max-size=$CCACHE_SIZE
+      #     ./autogen.sh
+      #     ./configure --prefix=`pwd`/depends/${{ matrix.host }} ${{ matrix.config-opts }} HOST=${{ matrix.host }} || ( cat config.log && false)
 
-      - name: build libdogecoin
-        run: |
-          make -j"$(getconf _NPROCESSORS_ONLN)" SPEED=slow V=1
-          mkdir -p ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}
-          if ([ "${{ matrix.name }}" == "x86_64-win" ] || [ "${{ matrix.name }}" == "i686-win" ]); then
-              cp .libs/* such.exe sendtx.exe ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}/
-          else
-              cp .libs/* such sendtx ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}/
-          fi
-          chmod +x ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}/*
+      # - name: build libdogecoin
+      #   run: |
+      #     make -j"$(getconf _NPROCESSORS_ONLN)" SPEED=slow V=1
+      #     mkdir -p ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}
+      #     if ([ "${{ matrix.name }}" == "x86_64-win" ] || [ "${{ matrix.name }}" == "i686-win" ]); then
+      #         cp .libs/* such.exe sendtx.exe ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}/
+      #     else
+      #         cp .libs/* such sendtx ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}/
+      #     fi
+      #     chmod +x ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}/*
 
-      - name: test libdogecoin
-        if: ${{ matrix.run-tests }}
-        run: |
-            case "${{ matrix.name }}" in
-              "armhf-linux") 
-              qemu-arm -E LD_LIBRARY_PATH=/usr/arm-linux-gnueabihf/lib/ /usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3 ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}/tests
-              ;;
-              "aarch64-linux") 
-              qemu-aarch64 -E LD_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib/ /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}/tests
-              ;;
-              "x86_64-win")
-              make check -j"$(getconf _NPROCESSORS_ONLN)" V=1
-              ;;
-              "i686-win") 
-              make check -j"$(getconf _NPROCESSORS_ONLN)" V=1
-              ;;
-              "x86_64-macos") 
-              ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}/tests
-              ;;
-              "x86_64-linux-dbg") 
-              make check -j"$(getconf _NPROCESSORS_ONLN)" V=1
-              python3 tooltests.py
-              ./wrappers/python/pytest/cython_tests.sh -host=${{ matrix.host }}
-              ./wrappers/golang/libdogecoin/build.sh
-              ;;
-              "i686-linux") 
-              make check -j"$(getconf _NPROCESSORS_ONLN)" V=1
-              ;;
-            esac
+      # - name: test libdogecoin
+      #   if: ${{ matrix.run-tests }}
+      #   run: |
+      #       case "${{ matrix.name }}" in
+      #         "armhf-linux") 
+      #         qemu-arm -E LD_LIBRARY_PATH=/usr/arm-linux-gnueabihf/lib/ /usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3 ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}/tests
+      #         ;;
+      #         "aarch64-linux") 
+      #         qemu-aarch64 -E LD_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib/ /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}/tests
+      #         ;;
+      #         "x86_64-win")
+      #         make check -j"$(getconf _NPROCESSORS_ONLN)" V=1
+      #         ;;
+      #         "i686-win") 
+      #         make check -j"$(getconf _NPROCESSORS_ONLN)" V=1
+      #         ;;
+      #         "x86_64-macos") 
+      #         ./build/libdogecoin-${{ github.sha }}-${{ matrix.name }}/tests
+      #         ;;
+      #         "x86_64-linux-dbg") 
+      #         make check -j"$(getconf _NPROCESSORS_ONLN)" V=1
+      #         python3 tooltests.py
+      #         ./wrappers/python/pytest/cython_tests.sh -host=${{ matrix.host }}
+      #         ./wrappers/golang/libdogecoin/build.sh
+      #         ;;
+      #         "i686-linux") 
+      #         make check -j"$(getconf _NPROCESSORS_ONLN)" V=1
+      #         ;;
+      #       esac
 
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          name: libdogecoin-${{ github.sha }}-${{ matrix.name }}
-          path: |
-            ${{ github.workspace }}/build/libdogecoin-${{ github.sha }}-${{ matrix.name }}
+      # - name: Upload artifacts
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: libdogecoin-${{ github.sha }}-${{ matrix.name }}
+      #     path: |
+      #       ${{ github.workspace }}/build/libdogecoin-${{ github.sha }}-${{ matrix.name }}
